# Generated by Django 2.2.2 on 2019-06-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('no_of_pages', models.IntegerField()),
                ('rack_number', models.IntegerField()),
            ],
            options={
                'ordering': ('book_name',),
            },
        ),
    ]
